### ISSUE TITLE
Request: use nmtree ("NetBSD's mtree") instead

### ISSUE THREAD

**Issue by johnnybubonic** [archiecobbs/mtree-port#11]
i believe i may have the answer to issue #5 , and a suggestion for a better port:

FreeBSD has [moved](https://lists.freebsd.org/pipermail/freebsd-current/2012-December/038697.html) the default "mtree" to "nmtree" (NetBSD's mtree).

- it's cleaner
- it works with libarchive's bsdtar (the exact version of bsdtar that #5 references)
- but it also works with e.g. FreeBSD's "legacy" mtree ("omtree", or "old mtree", i believe, is what it is)
- it updates infrequently, so re-porting won't be a very common occurrence (the last change to the code was 4 years ago)

you can grab it via ftp: ftp://ftp.NetBSD.org:/pub/pkgsrc/current/pkgsrc/pkgtools/mtree/files

**Comment by archiecobbs** [comment]
Thanks. FYI I'm too busy to dive into this right now but hopefully can sometime later.

**Comment by johnnybubonic** [comment]
no worries, much appreciated! i'd provide a patch myself, but i unfortunately only know python. :)

i'd be willing to put a bounty on this, if it helps (and would like to throw some beer money your way regardless); your project is immensely important:

- there currently is no GNU/native Linux coreutils mtree (why? i have no idea. seems like a huge oversight, if you ask me, on GNU/FSF's part, but... I digress.)
- it's **incredibly** useful
- it greatly assists in cross-platform compatibility

if a bounty would help, you can find contact info [here](https://square-r00t.net/gpg-info/#contact).

**Comment by yan12125** [comment]
I gave it a try on Arch Linux. It turns out to be extremely simple - I don't need to write a line of C code, just some packaging scripts!

Building NetBSD's mtree requires libnbcompat, which is also part of NetBSD. Packaging scripts for libnbcompat can be found on AUR [1]. Here's that for mtree: (I copied and modified from libnbcompat's script)
```Bash
# Maintainer: Timothy Redaelli <timothy.redaelli@gmail.com>

pkgname="mtree"
pkgver=20171109
pkgrel=1
pkgdesc="NetBSD's mtree utility"
arch=('i686' 'x86_64')
url="http://www.netbsd.org/"
license=('BSD')
depends=('glibc')
# libnbcompat is linked statically
makedepends=('bmake' 'cvs' 'libnbcompat')

_cvsroot=":pserver:anoncvs@anoncvs.NetBSD.org:/cvsroot"
_cvsmod="pkgsrc/pkgtools/$pkgname/files"

build() {
  cd "$srcdir"
  msg "Connecting to NetBSD CVS server...."

  if [[ -d "$_cvsmod/CVS" ]]; then
    cd "$_cvsmod"
    cvs -z3 update -d
  else
    cvs -z3 -d "$_cvsroot" co -D "$pkgver" -f "$_cvsmod"
    cd "$_cvsmod"
  fi

  msg "CVS checkout done or server timeout"
  msg "Starting build..."

  rm -rf "$srcdir/$_cvsmod-build"
  cp -r "$srcdir/$_cvsmod" "$srcdir/$_cvsmod-build"
  cd "$srcdir/$_cvsmod-build"

  ./configure --prefix=/usr --sbindir=/usr/bin LIBS="-lnbcompat"

  bmake
}

package() {
  cd "$srcdir/$_cvsmod-build"

  bmake install DESTDIR="$pkgdir/"
}
```

[1] https://aur.archlinux.org/packages/libnbcompat/

**Comment by jgoerzen** [comment]
I should note, incidentally, that getfacl/setfacl serves a somewhat similar purpose on Linux (though each have some features the other lacks), but with a different file format.

**Comment by johnnybubonic** [comment]
also, fwiw, i've implented it as an Arch AUR package (thanks, yan! couldn't have done it without you) called [nmtree](https://aur.archlinux.org/packages/nmtree). so this can be closed if desired, but i'd recommend leaving it open until resolution -- i have a suspicion that all versions except the netbsd version of mtree are considered obsolete by their upstream (though i only know of that and freebsd's version).

**Comment by archiecobbs** [comment]
I've created a new Linux port based on the NetBSD code.

Please check out these new repos:
* https://github.com/archiecobbs/libnbcompat
* https://github.com/archiecobbs/nmtree

I've only done very minimal testing. Let me know if this looks like it works for you. Thanks.
