### ISSUE TITLE
Missing files, broken autoconf/automake

### ISSUE THREAD

**Issue by brucelilly** [archiecobbs/mtree-port#14]
File INSTALL states:
  "./configure && make && sudo make install"
but there is no ./configure (nor makefile) in the source distribution.

Attempting to generate with multiple passes of autoconf ; aclocal and automake
(as well as mkdir scripts) yields only errors, starting with:
configure.ac:7: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:52: error: possibly undefined macro: AM_CONFIG_HEADER
and
configure.ac:6: error: required directory ./scripts does not exist
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:26: error: required file 'scripts/install-sh' not found
configure.ac:26:   'automake --add-missing' can install 'install-sh'
Makefile.am: error: required file './NEWS' not found
Makefile.am: error: required file './AUTHORS' not found
Makefile.am: error: required file './ChangeLog' not found
Makefile.am: error: required file 'scripts/depcomp' not found
Makefile.am:   'automake --add-missing' can install 'depcomp'
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again

and ending with:
configure.ac:52: error: required file 'config.h.in' not found
and
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'

[FWIW, this started by trying to track down why binary distributions of (apparently 1.04 --
no embedded strings for what(1) or ident(1)) mtree on Linux (openSUSE) do not in fact
work with many keywords listed in the man page, specifically most of the digest-related
keywords (md5digest, sha1digest, sha256digest, ripemd160digest, etc.); so in addition
to the problems getting the package to build, there are certainly version-identification
issues and probably functionality and documentation issues.]

**Comment by archiecobbs** [comment]
This project uses GNU autoconf, etc.

It sounds like you are trying to build from the git source instead of the distribution tarball.

Try instead downloading the distribution tarball from here: https://github.com/archiecobbs/mtree-port/wiki/Downloads

**Comment by brucelilly** [comment]
Yep, from the Github [Code] button.
The .tgz file builds OK, but then there's the problem(s) mentioned at the end of the original; I'll close this one and open a new one for that.
